- name: Publish Test Results
  uses: EnricoMi/publish-unit-test-result-action/composite@v2
  if: always()
  with:
    junit_files: "test-results/junit/**/*.xml"
    nunit_files: "test-results/nunit/**/*.xml"
    xunit_files: "test-results/xunit/**/*.xml"
    trx_files: "test-results/**/*.trx"
